ARG GO_IMAGE=golang:latest

FROM ${GO_IMAGE}

ENV CGO_ENABLED=0

RUN go build -a -i std

WORKDIR /go/src/github.com/creack/partypher

ADD vendor/ vendor/

RUN go build -i ./vendor/...

ENV GOFLAGS='-mod=vendor'

ADD Makefile main.go main_test.go ./
ADD api     ./api
ADD db      ./db
